name: Run Jest Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout código
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'

            - name: Instalar dependências
              run: npm install

            - name: Rodar testes com Jest
              run: npm test